# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Dreambudget"
  pageRef = "dreambudget"
  weight = 10

# [[main]]
#   name = "Docs"
#   pageRef = "docs"
#   weight = 20
# 
# [[main]]
#   name = "Samples"
#   pageRef = "samples"
#   weight = 30
# 
# [[main]]
#   name = "Users"
#   pageRef = "users"
#   weight = 40
# 
# [[main]]
#   identifier = "search"
#   weight = 50
#   [main.params]
#     action = "search"

[[main]]
  name = "Youtube"
  url = "https://youtube.com/@withedgar"
  weight = 20
  [main.params]
    icon = "youtube"
    showName = false
    target = "_blank"      

[[main]]
  name = "Instagram"
  url = "https://instagram.com/withedgar.me"
  weight = 30
  [main.params]
    icon = "instagram"
    showName = false
    target = "_blank"  

[[main]]
  name = "GitHub"
  url = "https://github.com/edbrsk"
  weight = 40
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "locale"
  weight = 99
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
